language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"

matrix:
  allow_failures:
    # sphinx doesn't support python 3.2
    - python: "pypy3"

install:
  - pip install tox
  - pip install -r doc-requirements.txt -e .

script:
  - tox -e $(./devscripts/travis-tox-env.sh $TRAVIS_PYTHON_VERSION)
  - cd docs; make html
